import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>Welcome to Admin Page!</div>
      </main>

      {/* <footer className={styles.footer}></footer> */}
    </div>
  );
};

export default Home;
